### ISSUE TITLE
Is it possible to extract tumor-only gene expression profile for whole transcriptome?

### ISSUE THREAD

**Issue by lxhuang7** [wwylab/DeMixT#13]
Hi, Thanks for this wonderful tool. I'm trying to switch from ISOpure to DeMixT. One question though, can I extract tumor-only expression matrix for all genes in my admixed RNA-seq data by just setting if.filter = FALSE? Do I need to change other parameters accordingly? It is not very clear to me in the vignette. Thanks again!

**Comment by ShaolongCao** [comment]
"if.filter = FALSE" will force DeMixT algorithm to use all available genes to fit the deconvolution model, which is not recommended. We suggest to use "if.filter = TRUE" option, which will improve tumor proportion estimation. Currently, we have a built-in filter in the function DeMixT_S2 to filter out unidentifiable genes in terms of the deconvolved expression (tumor-only expression). Consequently, it is likely that some genes will be dropped since the deconvolved expression value will be unreliable.

**Comment by lxhuang7** [comment]
Thank you very much for the explanation.

**Comment by guodudou** [comment]
@lxhuang7 Hello! Sorry for bothering you. I am trying to identity a tool for tumor profile deconvolution and have ISOpure and DeMixT. I am curious what are the reasons for you to switch from ISOpure to DeMixT? Thanks!
